services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "5500:5500"

  server:
    build: 
      context: .
      dockerfile: server/Dockerfile
    command: sh -c "uvicorn run:app --reload --port=8001 --host=0.0.0.0"
    ports:
      - "8001:8001"